In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import cv2
import numpy as np

In [4]:
img=cv2.imread(r"C:\Users\SSS\Downloads\download.jpg")   # default colour space is RGB default 1,when0-grey scale

Above is color image

In [6]:
img.shape

(159, 106, 3)

In [28]:
img

array([[[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       ...,

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [15, 15, 15],
        [12, 12, 12],
        [12, 12, 12]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [10, 10, 10],
        [ 8,  8,  8],
        [ 8,  8,  8]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 8,  8,  8],
        [ 7,  7,  7],
        [ 7,  7,  7]]], dtype=uint8)

In [27]:
cv2.imshow("download",img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [10]:
cv2.imwrite(r"C:\Users\SSS\Desktop\New folder (2)\1.jpg",img)

True

In [17]:
img1=np.zeros((100,100),dtype=np.uint8)

In [18]:
img1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [19]:
cv2.imshow("black",img1)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [20]:
img2=np.full((100,100),255,dtype=np.uint8)

In [26]:
cv2.imshow("white",img2)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [22]:
img2

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [38]:
img3=cv2.imread(r"C:\Users\SSS\Downloads\color.jpg",0)

In [39]:
img3.shape

(129, 129)

In [40]:
img3[0,0]

204

In [41]:
cv2.imshow("hghkk",img3)
cv2.waitKey(10000)
cv2.destroyAllWindows()

RGB but store in BGR

In [43]:
img4=cv2.imread(r"C:\Users\SSS\Downloads\color.jpg",1)

In [44]:
im=cv2.cvtColor(img4,cv2.COLOR_BGR2HSV)

In [45]:
im[0,0]

array([170,  67, 247], dtype=uint8)

In [46]:
im.shape

(129, 129, 3)

In [48]:
cv2.imshow("whfrr",im)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [2]:
vi=cv2.VideoCapture(r"C:\Users\SSS\Downloads\dipper_chicks_feeding_bird_songbird_962.mp4")

vi-have video object(frame),have attribute read()
waitkey always have -1 if u dont press key that'swhy waitkey(1)==ord("q")

In [3]:
while True:
    su,img=vi.read()
    cv2.imshow("video",img)
    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()        

In [3]:
while True:
    su,img=vi.read()
    print(su)
    cv2.imshow("video",img)
    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\SSS'

In [4]:
os.chdir(r"C:\video nlp")

In [5]:
os.getcwd()

'C:\\video nlp'

In [ ]:
vid=cv2.VideoCapture(0)
count=0
while True:
    count=count+1
    su,img=vid.read()
    if su==True:
        cv2.imshow("video",img)
        cv2.imwrite(r"C:\video nlp\{}.jpg".format(count),img)

    if cv2.waitKey(1)==ord("q"):
        break
cv2.destroyAllWindows()

In [ ]:
for y in os.listdir():
    cv2.imread(y)

Image transformation


In [3]:
import cv2

In [20]:
img=cv2.imread(r"C:\Users\SSS\Downloads\flower.jpg")

In [21]:
img.shape

(238, 212, 3)

In [22]:
img.shape[1]

212

In [23]:
img.shape[1]/2

106.0

In [24]:
import numpy as np

In [35]:
t=np.array(([[1,0,img.shape[1]/4],[1,0,img.shape[0]/4]]))  # shift in both x and y axis

In [36]:
imgt=cv2.warpAffine(img,t,img.shape[0:2])

In [37]:
cv2.imshow("whfr",imgt)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [38]:
tr=np.array(([[1,0,img.shape[1]/4],[1,0,0]])) # shift in x axis

In [39]:
imgtr=cv2.warpAffine(img,tr,img.shape[0:2])

In [40]:
cv2.imshow("whfr",imgtr)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [41]:
trs=np.array(([[1,0,0],[1,0,img.shape[0]/6]])) # shift in y axis

In [42]:
imgtrs=cv2.warpAffine(img,trs,img.shape[0:2])

In [43]:
cv2.imshow("whfr",imgtrs)
cv2.waitKey(10000)
cv2.destroyAllWindows()

Rotation

In [44]:
img.shape[1]/2
img.shape[0]/2

119.0

In [45]:
rt=cv2.getRotationMatrix2D((img.shape[0]/2,img.shape[1]/2),180,0.5)  # rotate in 180 degree,
#scaling default-1,0.5-scaling down

In [46]:
ims=cv2.warpAffine(img,rt,img.shape[0:2])

In [47]:
cv2.imshow("whfr",ims)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [48]:
img.shape

(238, 212, 3)

In [50]:
im1=cv2.resize(img,(200,200))

In [51]:
im1.shape

(200, 200, 3)

In [52]:
cv2.imshow("whfr",im1)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [ ]:
# cropping

In [95]:
img[41:60,114:145]

array([[[252, 207, 140],
        [252, 207, 140],
        [252, 207, 140],
        ...,
        [252, 207, 140],
        [252, 207, 140],
        [252, 207, 140]],

       [[252, 207, 140],
        [252, 207, 140],
        [252, 207, 140],
        ...,
        [252, 207, 140],
        [252, 207, 140],
        [252, 207, 140]],

       [[252, 207, 140],
        [252, 207, 140],
        [252, 207, 140],
        ...,
        [252, 207, 140],
        [252, 207, 140],
        [252, 207, 140]],

       ...,

       [[252, 204, 146],
        [254, 205, 143],
        [255, 206, 140],
        ...,
        [239, 200, 138],
        [249, 217, 164],
        [248, 215, 170]],

       [[254, 204, 146],
        [255, 205, 143],
        [255, 206, 139],
        ...,
        [243, 206, 148],
        [237, 208, 163],
        [193, 165, 130]],

       [[254, 204, 144],
        [255, 205, 142],
        [255, 206, 139],
        ...,
        [245, 211, 157],
        [216, 190, 153],
        [ 68,  44,  20]]

In [96]:
cv2.imshow("wh",im1[41:60,114:145])
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [56]:
img.shape

(238, 212, 3)

In [57]:
b,g,r=cv2.split(img)

In [58]:
b

array([[252, 252, 252, ..., 252, 252, 252],
       [252, 252, 252, ..., 252, 252, 252],
       [252, 252, 252, ..., 252, 252, 252],
       ...,
       [252, 252, 252, ..., 252, 252, 252],
       [252, 252, 252, ..., 252, 252, 252],
       [252, 252, 252, ..., 252, 252, 252]], dtype=uint8)

In [59]:
g

array([[207, 207, 207, ..., 207, 207, 207],
       [207, 207, 207, ..., 207, 207, 207],
       [207, 207, 207, ..., 207, 207, 207],
       ...,
       [207, 207, 207, ..., 207, 207, 207],
       [207, 207, 207, ..., 207, 207, 207],
       [207, 207, 207, ..., 207, 207, 207]], dtype=uint8)

In [60]:
r

array([[140, 140, 140, ..., 140, 140, 140],
       [140, 140, 140, ..., 140, 140, 140],
       [140, 140, 140, ..., 140, 140, 140],
       ...,
       [140, 140, 140, ..., 140, 140, 140],
       [140, 140, 140, ..., 140, 140, 140],
       [140, 140, 140, ..., 140, 140, 140]], dtype=uint8)

In [62]:
cv2.imshow("whfrwee",cv2.merge([b,g,r]))
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [81]:
img.shape

(238, 212, 3)

In [73]:
b,g,r=cv2.split(img)

In [87]:
a=np.full(img.shape[0:2],0,dtype=np.uint8)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [88]:
a.shape

(238, 212)

In [90]:
cv2.imshow("whfrwe",cv2.merge([a,g,a]))
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [91]:
cv2.imshow("whfrwe",cv2.merge([a,g+100,a]))
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [92]:
cv2.imshow("whfrwe",cv2.merge([b*0,g*0,r]))  # only red color
cv2.waitKey(10000)
cv2.destroyAllWindows()